services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - psibase_net
    restart: unless-stopped 