services:
  proxy:
    image: "nginx:1.27"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./nginx/
        target: /etc/nginx/
      - type: volume
        source: letsencrypt-certs-volume
        target: /letsencrypt/certs
    environment:
      - HOST=${HOST}
      - ADMIN_HOST=${ADMIN_HOST}
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
    networks:
      - psibase_net

networks:
  psibase_net:
    driver: bridge 