include:
  - docker-compose.softhsm.yml
  - docker-compose.psinode.yml
  - docker-compose.proxy.yml
  - docker-compose.dozzle.yml
  # - docker-compose.ddclient.yml

networks:
  psibase_net:
    name: psibase_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1