services:
  psinode:
    image: "${PSINODE_IMAGE}"
    user: root
    ports:
      - '8090:8090'
    ulimits:
      memlock: -1
      core: -1
    entrypoint: ["/scripts/psinode-entrypoint.sh"]
    environment:
      - PRODUCER_NAME=${PRODUCER_NAME}
      - HOST=${HOST}
      - DB_CACHE_SIZE=${DB_CACHE_SIZE}
      - PSIBASE_ADMIN_IP=${PSIBASE_ADMIN_IP}
    volumes:
      - psinode-volume:/root/psibase
      - softhsm-keys:/var/lib/softhsm/tokens
      - softhsm-lib:/softhsm-lib
      - ./psinode-entrypoint.sh:/scripts/psinode-entrypoint.sh:ro
      - ./traefik/auth:/etc/traefik/auth:ro
    networks:
      psibase_net:
        ipv4_address: 172.30.0.20
    depends_on:
      - softhsm

volumes:
  psinode-volume:
  softhsm-keys:
  softhsm-lib: