include:
  - docker-compose.softhsm.yml
  - docker-compose.psinode.yml
  - docker-compose.proxy.yml
  - docker-compose.dozzle.yml
  # - docker-compose.ddclient.yml

networks:
  psibase_net:
    name: psibase_net
    driver: bridge
