services:
  psinode:
    image: "${PSINODE_IMAGE}"
    user: root
    ports:
      - '8090:8090'
    ulimits:
      memlock: -1
    command: [
      "db",
      "-p", "${PRODUCER_NAME}",
      "-o", "${HOST}",
      "--p2p",
      "-l", "8090",
      "--admin-authz=rw:any",
      "--database-cache-size=${DB_CACHE_SIZE}",
      "--pkcs11-module=/usr/lib/softhsm/libsofthsm2.so"
    ]
    volumes:
      - psinode-volume:/root/
      - softhsm-keys:/var/lib/softhsm/tokens
      - ./traefik/auth:/etc/traefik/auth:ro
    networks:
      - psibase_net

volumes:
  psinode-volume:
  softhsm-keys: