services:
  reverse-proxy:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}"
      - "TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL=${EMAIL}"
      - "HOST=${HOST}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme:/etc/traefik/acme" # needs to be rw, otherwise cert issuance fails
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/config:/etc/traefik/config:ro"
      - "./traefik/auth:/etc/traefik/auth:ro"
    networks:
      psibase_net:
        ipv4_address: 172.30.0.10
