services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "./ddclient:/config"
    restart: unless-stopped
    networks:
      psibase_net:
        ipv4_address: 172.30.0.50
