http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
    
    psinode-headers:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
    
    psinode-rewrite:
      redirectRegex:
        regex: "^http://([^/:]+)(:[0-9]+)?/(.*)$$"
        replacement: "https://${1}/${3}"

    strip-auth-header:
      headers:
        customRequestHeaders:
          X-Auth-User: ""
          Remote-User: ""

    admin-auth:
      forwardAuth:
        address: 'http://authelia:9091/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name 