tlsCommon: &tlsCommon
  certResolver: cloudflare
  domains:
    - main: "{{ env "HOST" }}"
      sans: ["*.{{ env "HOST" }}"]

http:
  routers:
    psinode:
      rule: Host(`{{ env "HOST" }}`) || (HostRegexp(`^.+\.{{ env "HOST" }}$`) && !Host(`x-admin.{{ env "HOST" }}`) && !Host(`x-traefik.{{ env "HOST" }}`))
      service: "psinode"
      entryPoints:
        - web
        - websecure
      middlewares:
        - security-headers
        - psinode-headers
        - psinode-rewrite
      tls: *tlsCommon

    admin:
      rule: Host(`x-admin.{{ env "HOST" }}`)
      service: "psinode"
      entryPoints:
        - websecure
      middlewares:
        - security-headers
        - admin-auth
      tls: *tlsCommon
        
    dashboard:
      rule: Host(`x-traefik.{{ env "HOST" }}`)
      service: "api@internal"
      entryPoints:
        - websecure
      middlewares:
        - admin-auth
        - security-headers
      tls: *tlsCommon

  services:
    psinode:
      loadBalancer:
        servers:
          - url: "http://psinode:8090"
        passHostHeader: true 