tlsCommon: &tlsCommon
  certResolver: cloudflare
  domains:
    - main: "{{ env "HOST" }}"
      sans: ["*.{{ env "HOST" }}"]

http:
  routers:
    psinode:
      rule: Host(`{{ env "HOST" }}`) || (HostRegexp(`^.+\.{{ env "HOST" }}$`) && !HostRegexp(`^x-.+\.{{ env "HOST" }}$`))
      service: "psinode"
      entryPoints:
        - web
        - websecure
      middlewares:
        - security-headers
        - strip-auth-header
        - psinode-headers
        - psinode-rewrite
      tls: *tlsCommon

    x-peers-p2p:
      rule: Host(`x-peers.{{ env "HOST" }}`) && Path(`/p2p`) && Method(`GET`)
      service: "psinode"
      entryPoints:
        - websecure
      priority: 100
      middlewares:
        - security-headers
        - strip-auth-header
        - admin-auth
        - psinode-headers
      tls: *tlsCommon

    x-services:
      rule: HostRegexp(`^x-.+\.{{ env "HOST" }}$`) && !Host(`x-traefik.{{ env "HOST" }}`) && !Host(`x-logs.{{ env "HOST" }}`) && !Host(`x-disk.{{ env "HOST" }}`) && !Host(`x-auth.{{ env "HOST" }}`)
      service: "psinode"
      entryPoints:
        - websecure
      middlewares:
        - security-headers
        - strip-auth-header
        - admin-auth
      tls: *tlsCommon
        
    dashboard:
      rule: Host(`x-traefik.{{ env "HOST" }}`)
      service: "api@internal"
      entryPoints:
        - websecure
      middlewares:
        - strip-auth-header
        - admin-auth
        - security-headers
      tls: *tlsCommon

    logs:
      rule: Host(`x-logs.{{ env "HOST" }}`)
      service: "dozzle"
      entryPoints:
        - websecure
      middlewares:
        - strip-auth-header
        - security-headers
        - admin-auth
      tls: *tlsCommon

    disk:
      rule: Host(`x-disk.{{ env "HOST" }}`)
      service: "qdirstat"
      entryPoints:
        - websecure
      middlewares:
        - strip-auth-header
        - security-headers
        - admin-auth
      tls: *tlsCommon

    auth:
      rule: Host(`x-auth.{{ env "HOST" }}`)
      service: "authelia"
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      tls: *tlsCommon

  services:
    psinode:
      loadBalancer:
        servers:
          - url: "http://psinode:8090"
        passHostHeader: true 

    dozzle:
      loadBalancer:
        servers:
          - url: "http://dozzle:8080"
        passHostHeader: true

    qdirstat:
      loadBalancer:
        servers:
          - url: "http://qdirstat:5800"
        passHostHeader: true

    authelia:
      loadBalancer:
        servers:
          - url: "http://authelia:9091"
        passHostHeader: true

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: cloudflare
        domain:
          main: "{{ env "HOST" }}"
          sans: ["*.{{ env "HOST" }}"]